// Copyright (c) 2022, KUNLUNXIN CORPORATION. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// WARNING: THIS FILE WAS AUTOMATICALLY GENERATED.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package xpuml

/*
#cgo LDFLAGS: -Wl,--unresolved-symbols=ignore-in-object-files
#cgo CFLAGS: -DXPUML_NO_UNVERSIONED_FUNC_DEFS=1
#include "xpuml.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// xpumlInit_v1 function as declared in xpuml/xpuml.h
func xpumlInit_v1() Return {
	__ret := C.xpumlInit()
	__v := (Return)(__ret)
	return __v
}

// xpumlShutdown function as declared in xpuml/xpuml.h
func xpumlShutdown() Return {
	__ret := C.xpumlShutdown()
	__v := (Return)(__ret)
	return __v
}

// xpumlErrorString function as declared in xpuml/xpuml.h
func xpumlErrorString(Result Return) string {
	cResult, _ := (C.xpumlReturn_t)(Result), cgoAllocsUnknown
	__ret := C.xpumlErrorString(cResult)
	__v := packPCharString(__ret)
	return __v
}

// xpumlSystemGetDriverVersion function as declared in xpuml/xpuml.h
func xpumlSystemGetDriverVersion(Version *byte, Length uint32) Return {
	cVersion, _ := (*C.char)(unsafe.Pointer(Version)), cgoAllocsUnknown
	cLength, _ := (C.uint)(Length), cgoAllocsUnknown
	__ret := C.xpumlSystemGetDriverVersion(cVersion, cLength)
	__v := (Return)(__ret)
	return __v
}

// xpumlSystemGetXPUMLVersion function as declared in xpuml/xpuml.h
func xpumlSystemGetXPUMLVersion(Version *byte, Length uint32) Return {
	cVersion, _ := (*C.char)(unsafe.Pointer(Version)), cgoAllocsUnknown
	cLength, _ := (C.uint)(Length), cgoAllocsUnknown
	__ret := C.xpumlSystemGetXPUMLVersion(cVersion, cLength)
	__v := (Return)(__ret)
	return __v
}

// xpumlDeviceGetCount_v1 function as declared in xpuml/xpuml.h
func xpumlDeviceGetCount_v1(DeviceCount *uint32) Return {
	cDeviceCount, _ := (*C.uint)(unsafe.Pointer(DeviceCount)), cgoAllocsUnknown
	__ret := C.xpumlDeviceGetCount(cDeviceCount)
	__v := (Return)(__ret)
	return __v
}

// xpumlDeviceGetAttributes_v1 function as declared in xpuml/xpuml.h
func xpumlDeviceGetAttributes_v1(Device Device, Attributes *DeviceAttributes) Return {
	cDevice, _ := *(*C.xpumlDevice_t)(unsafe.Pointer(&Device)), cgoAllocsUnknown
	cAttributes, _ := (*C.xpumlDeviceAttributes_t)(unsafe.Pointer(Attributes)), cgoAllocsUnknown
	__ret := C.xpumlDeviceGetAttributes(cDevice, cAttributes)
	__v := (Return)(__ret)
	return __v
}

// xpumlDeviceGetHandleByIndex_v1 function as declared in xpuml/xpuml.h
func xpumlDeviceGetHandleByIndex_v1(Index uint32, Device *Device) Return {
	cIndex, _ := (C.uint)(Index), cgoAllocsUnknown
	cDevice, _ := (*C.xpumlDevice_t)(unsafe.Pointer(Device)), cgoAllocsUnknown
	__ret := C.xpumlDeviceGetHandleByIndex(cIndex, cDevice)
	__v := (Return)(__ret)
	return __v
}

// xpumlDeviceGetPciInfo_v1 function as declared in xpuml/xpuml.h
func xpumlDeviceGetPciInfo_v1(Device Device, Pci *PciInfo) Return {
	cDevice, _ := *(*C.xpumlDevice_t)(unsafe.Pointer(&Device)), cgoAllocsUnknown
	cPci, _ := (*C.xpumlPciInfo_t)(unsafe.Pointer(Pci)), cgoAllocsUnknown
	__ret := C.xpumlDeviceGetPciInfo(cDevice, cPci)
	__v := (Return)(__ret)
	return __v
}

// xpumlDeviceGetClockInfo function as declared in xpuml/xpuml.h
func xpumlDeviceGetClockInfo(Device Device, _type ClockType, Clock *uint32) Return {
	cDevice, _ := *(*C.xpumlDevice_t)(unsafe.Pointer(&Device)), cgoAllocsUnknown
	c_type, _ := (C.xpumlClockType_t)(_type), cgoAllocsUnknown
	cClock, _ := (*C.uint)(unsafe.Pointer(Clock)), cgoAllocsUnknown
	__ret := C.xpumlDeviceGetClockInfo(cDevice, c_type, cClock)
	__v := (Return)(__ret)
	return __v
}

// xpumlDeviceGetState_v1 function as declared in xpuml/xpuml.h
func xpumlDeviceGetState_v1(Device Device, State *DeviceState) Return {
	cDevice, _ := *(*C.xpumlDevice_t)(unsafe.Pointer(&Device)), cgoAllocsUnknown
	cState, _ := (*C.xpumlDeviceState_t)(unsafe.Pointer(State)), cgoAllocsUnknown
	__ret := C.xpumlDeviceGetState(cDevice, cState)
	__v := (Return)(__ret)
	return __v
}

// xpumlDeviceGetTemperature function as declared in xpuml/xpuml.h
func xpumlDeviceGetTemperature(Device Device, SensorType TemperatureSensors, Temp *uint32) Return {
	cDevice, _ := *(*C.xpumlDevice_t)(unsafe.Pointer(&Device)), cgoAllocsUnknown
	cSensorType, _ := (C.xpumlTemperatureSensors_t)(SensorType), cgoAllocsUnknown
	cTemp, _ := (*C.uint)(unsafe.Pointer(Temp)), cgoAllocsUnknown
	__ret := C.xpumlDeviceGetTemperature(cDevice, cSensorType, cTemp)
	__v := (Return)(__ret)
	return __v
}

// xpumlDeviceGetPowerUsage function as declared in xpuml/xpuml.h
func xpumlDeviceGetPowerUsage(Device Device, Power *uint32) Return {
	cDevice, _ := *(*C.xpumlDevice_t)(unsafe.Pointer(&Device)), cgoAllocsUnknown
	cPower, _ := (*C.uint)(unsafe.Pointer(Power)), cgoAllocsUnknown
	__ret := C.xpumlDeviceGetPowerUsage(cDevice, cPower)
	__v := (Return)(__ret)
	return __v
}

// xpumlDeviceGetMemoryInfo function as declared in xpuml/xpuml.h
func xpumlDeviceGetMemoryInfo(Device Device, Memory *Memory) Return {
	cDevice, _ := *(*C.xpumlDevice_t)(unsafe.Pointer(&Device)), cgoAllocsUnknown
	cMemory, _ := (*C.xpumlMemory_t)(unsafe.Pointer(Memory)), cgoAllocsUnknown
	__ret := C.xpumlDeviceGetMemoryInfo(cDevice, cMemory)
	__v := (Return)(__ret)
	return __v
}

// xpumlDeviceGetBoardId function as declared in xpuml/xpuml.h
func xpumlDeviceGetBoardId(Device Device, BoardId *uint32) Return {
	cDevice, _ := *(*C.xpumlDevice_t)(unsafe.Pointer(&Device)), cgoAllocsUnknown
	cBoardId, _ := (*C.uint)(unsafe.Pointer(BoardId)), cgoAllocsUnknown
	__ret := C.xpumlDeviceGetBoardId(cDevice, cBoardId)
	__v := (Return)(__ret)
	return __v
}

// xpumlDeviceGetUtilizationRates function as declared in xpuml/xpuml.h
func xpumlDeviceGetUtilizationRates(Device Device, Utilization *Utilization) Return {
	cDevice, _ := *(*C.xpumlDevice_t)(unsafe.Pointer(&Device)), cgoAllocsUnknown
	cUtilization, _ := (*C.xpumlUtilization_t)(unsafe.Pointer(Utilization)), cgoAllocsUnknown
	__ret := C.xpumlDeviceGetUtilizationRates(cDevice, cUtilization)
	__v := (Return)(__ret)
	return __v
}

// xpumlDeviceGetComputeRunningProcesses_v1 function as declared in xpuml/xpuml.h
func xpumlDeviceGetComputeRunningProcesses_v1(Device Device, InfoCount *uint32, Infos *ProcessInfo) Return {
	cDevice, _ := *(*C.xpumlDevice_t)(unsafe.Pointer(&Device)), cgoAllocsUnknown
	cInfoCount, _ := (*C.uint)(unsafe.Pointer(InfoCount)), cgoAllocsUnknown
	cInfos, _ := (*C.xpumlProcessInfo_t)(unsafe.Pointer(Infos)), cgoAllocsUnknown
	__ret := C.xpumlDeviceGetComputeRunningProcesses(cDevice, cInfoCount, cInfos)
	__v := (Return)(__ret)
	return __v
}

// xpumlDeviceGetArchitecture function as declared in xpuml/xpuml.h
func xpumlDeviceGetArchitecture(Device Device, Arch *DeviceArchitecture) Return {
	cDevice, _ := *(*C.xpumlDevice_t)(unsafe.Pointer(&Device)), cgoAllocsUnknown
	cArch, _ := (*C.xpumlDeviceArchitecture_t)(unsafe.Pointer(Arch)), cgoAllocsUnknown
	__ret := C.xpumlDeviceGetArchitecture(cDevice, cArch)
	__v := (Return)(__ret)
	return __v
}

// xpumlDeviceGetHostVxpuMode_v1 function as declared in xpuml/xpuml.h
func xpumlDeviceGetHostVxpuMode_v1(Device Device, PHostVxpuMode *HostVxpuMode) Return {
	cDevice, _ := *(*C.xpumlDevice_t)(unsafe.Pointer(&Device)), cgoAllocsUnknown
	cPHostVxpuMode, _ := (*C.xpumlHostVxpuMode_t)(unsafe.Pointer(PHostVxpuMode)), cgoAllocsUnknown
	__ret := C.xpumlDeviceGetHostVxpuMode(cDevice, cPHostVxpuMode)
	__v := (Return)(__ret)
	return __v
}

// xpumlDeviceSetSriovVfNum_v1 function as declared in xpuml/xpuml.h
func xpumlDeviceSetSriovVfNum_v1(Device Device, VfNum int32) Return {
	cDevice, _ := *(*C.xpumlDevice_t)(unsafe.Pointer(&Device)), cgoAllocsUnknown
	cVfNum, _ := (C.int)(VfNum), cgoAllocsUnknown
	__ret := C.xpumlDeviceSetSriovVfNum(cDevice, cVfNum)
	__v := (Return)(__ret)
	return __v
}
