exclude: ^(pkg/xpuml/)
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/golangci/golangci-lint # golangci-lint hook repo
    rev: v1.44.2 # golangci-lint hook repo revision
    hooks:
    -   id: golangci-lint # hook id
